mode: PUBLIC # PUBLIC | LOCAL
poppler: E:\\Hoang Thang\\install\\poppler-23.11.0\\Library\\bin
document:
  folder: E:\Hoang Thang\Hackathon 2024\LLMs\doc
model:
  llm: 
    gpt4all:
      use: v1
      list:
        v1: model/ggml-model-gpt4all-falcon-q4_0.bin
        v2: model/gpt4all-falcon-newbpe-q4_0.gguf
    openai:
      use: gpt3.5
      list:
        gpt3.5: gpt-3.5-turbo
        davici: davinci-002
  embedding:
    sentence-transformers: sentence-transformers/all-MiniLM-L6-v2
openai:
  apikey: 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